### ISSUE TITLE
 Logo Proposal for PianOli

### ISSUE THREAD

**Issue by leonardoderoy** [nicolasbrailo/PianOli#1]
Hello! @nicolasbrailo
I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards
Leonardo Deroy 

Graphic Designer

**Comment by nicolasbrailo** [comment]
Hola @leonardoderoy! I'd love to work together with you on this project. Especially when it comes to design - an area where I'm not very skilled. Thank you for the offer!

A couple of things you may want to know first:

- I'm just starting to figure out how this app will work. I have no idea when it'll be ready to publish!
- Once it is ready, I may publish it to F-Droid. I'm not planning to publish it to Google's appstore, since I don't want to pay the registration fee. I'm OK if you want to publish to Google's appstore, though.
- Something I haven't quite figured out yet: the app may not be acceptable under any appstore's policy. My main goal with this app is stopping my daughter from closing it. This means blocking naive attempts at closing the app, such as using the back or home button. I have no idea if this is acceptable in any appstore.
- My kid will probably love it if you can make this app look nice :)

Still up for working together on this one?

Cheers!

**Comment by leonardoderoy** [comment]
Hi @nicolasbrailo  Perfect, I have no problem in making a logo for your application, I would like to know the exact name and what your project is about exactly

**Comment by nicolasbrailo** [comment]
Thanks @leonardoderoy!
I just updated the README.md with this brief description:

**Comment by leonardoderoy** [comment]
hi @nicolasbrailo  this information is enough soon I will be uploading my proposal
bro avisame si te transfiero el helado a ti a o rita de sales ford
