### ISSUE TITLE
When the app is opened for the first time no notes are played

### ISSUE THREAD

**Issue by yamatt** [nicolasbrailo/PianOli#25]
I found that when you first open the app straight after install the keys don't play any notes.

You must to go to the settings then set an instrument before the keys will play.

This can also replicated by going to the app info in the Android settings and selecting 'Clear Storage'.

It should have a default instrument when you first open it.

Thanks so much for doing this. It's a great app to have in a hurry when my 6 month old doesn't have his toys nearby.

**Comment by pserwylo** [comment]
Thanks for the report @yamatt.

@nicolasbrailo: Let me know if you want me to fix that up and send a PR. Happy for you too as well though, as it is your awesome project after all!

**Comment by nicolasbrailo** [comment]
Thanks for the report @yamatt 

@pserwylo please feel free to go ahead, I don't think I'll be able to work on it anytime soon. I added you as a contributor or admin to the project, haven't I? The first version was "mine", but by now I'd say you have as much right as I do to call it your project. Half of the code is yours by now anyway :)

**Comment by pserwylo** [comment]
Cool, I've tagged a new release with this fix as v1.12. While at it, I also tagged v1.11 first, so that F-Droid can build both of them hopefully. Mainly just for historical sake so that if something goes wrong with this latest release for whatever reason, the existing one is still in the F-Droid archive.

@yamatt could you please keep an eye out on F-Droid over the next week or so for the new version, and let us know if it addresses the issue for you? Thanks.

**Comment by yamatt** [comment]
Got the update. Confirming this has been fixed

**Comment by pserwylo** [comment]
Thanks for the confirmation.
