### ISSUE TITLE
Gets hang while multi-touch

### ISSUE THREAD

**Issue by mizzunet** [nicolasbrailo/PianOli#30]
The app becomes stuck when tap with multi-fingers, like three.
Could you confirm this not only here? If you could not I would share logs.

https://user-images.githubusercontent.com/10193999/122046388-7565f180-cdfc-11eb-9cc2-09b137d349fc.mp4

My device: OnePlus 5, Android 11

**Comment by nicolasbrailo** [comment]
Hi @mizzunet, I'm afraid I can't repro in my device, logs would be welcome. The app should be able to handle some degree of simultaneous presses (up to 5, I think?). Even if it can't, some of the animations may un-sync (ie a key may be shown as pressed when it isn't) but the app should still work.

Thanks for the report!

**Comment by mizzunet** [comment]
@nicolasbrailo here's the log https://transfer.sh/16SbUGX/Log_2021-06-15_17-24-50.txt

It's probably my device's problem then. However, I have played games where multi-touch required.

**Comment by nicolasbrailo** [comment]
@mizzunet I doubt very much it's a problem specific to your device. It's much more likely I did something stupid in my code than your device has a bug that's uniquely triggered by this app :)

That doesn't help us much, though, as the log has nothing to point me in the direction of what the problem may be. I can try building an apk with extra debug info, if you'd like? (Disclaimer: running apks from random people from the internet is a terrible idea from a security perspective, and it is much safer if you check out and build the code yourself - but I also understand if that's not an option for you)

**Comment by christgod** [comment]
Hi,
I'm having similar problems with the app getting stuck.
I finally figured out that the "back" gesture on my pixel 4a causes Pianoli to freeze. 
Back gesture using a Google Pixel 4a = swiping inwards from the left or right edge. Took me a while to figure out since it only happened when my daughter was playing with it...
Any ideas why this happens? I'm on vacation and have no possibility for checking the code myself atm.

Thanks for the app btw, my toddler really likes it... until she starts crying when it freezes 😀

**Comment by nicolasbrailo** [comment]
@christgod, sorry, I have no clue why this may be happening and I can't repro this myself. I'm more than happy to send you an apk with more debug logging (caveats about security from my comment above apply!) but there isn't much I can do without being able to reproduce this problem. I suspect there's something wrong when translating the touch-down/touch-up events from Android (https://github.com/nicolasbrailo/PianOli/blob/master/app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java#L260) because that's really the only complicated bit of code in the project, but I can't immediately see anything wrong with it.

**Comment by christgod** [comment]
If you can send me the APK I'd be happy to try it and send you the log if that helps.

**Comment by mizzunet** [comment]
@nicolasbrailo I changed ROM and guess what? Now, this doesn't happen. The bug was the ROM lol

**Comment by Magneticdud** [comment]
It also happens on three of my phones, all with miui (not custom rom)

which was pretty bad because for some reason the unlock procedure doesn't work. I have to press both gears then quit. If the app was hung, then I needed to force reboot the phone. And one of the phones when locked screen doesn't even show the power menu, so i had to reboot via adb

but looks like it's because a swipe with 3 fingers triggers a screenshot on default settings on those roms; i think the image popup of the screenshot is trying to appear and hangs the app.

I Disabled "screenshot with 3 finger swipe" and now looks like it's not hanging anymore

**Comment by nicolasbrailo** [comment]
Interesting! So there's a weird interaction between screenshots and locked apps. That's something I should look into. Thanks for updating!

**Comment by mizzunet** [comment]
@Magneticdud awesome, you might be right. I had enabled this option(three finger gesture for screenshot), then now I am LineageOS which does not offer this feature, also no hang as well

**Comment by christgod** [comment]
On my Pixel only the "back"  _gesture_ causes the app to get stuck. I switched to 3 button navigation, now everything is working fine, including the back button.

**Comment by nicolasbrailo** [comment]
With the hint that gestures were causing the problem, I was able to reproduce. The app should now just reset when something funky happens, and will only look weird until the next keystroke.

My guess is that Android sends a touch-down event, then the gesture is triggered and never sends the touch-up event. Eventually all keys got out of sync and the app just looked stuck.
