### ISSUE TITLE
App freeze after hitting one of the return or menu button 

### ISSUE THREAD

**Issue by rgarrigue** [nicolasbrailo/PianOli#33]
Hi there

My < 4 years old kids always end up freezing the app quickly : they hit one of the button part of the unpinning procedure, an message show up "hit both to unpin" or whatever message. After that the app becomes unresponsive, the keyboard being a bit greyed. I then have to unpin, unlock, refuse pinning, go back to the "desktop", close the app, start it again... a tad unnerving ! 

I understood you can't tune the pin/unpin feature which is part of Android & a bit phone dependent ? What can I do to send you the logs ?

Thanks for PianOli

**Comment by nicolasbrailo** [comment]
Hi @rgarrigue, it looks like you're seeing the same issues as https://github.com/nicolasbrailo/PianOli/issues/30. If that's the case, the problem should go away once the fix is picked up by fdroid (in the next one or two weeks, I think?).

If you can't wait until fdroid's release, remote/master should work fine.

**Comment by rgarrigue** [comment]
All good, thank you !
