### ISSUE TITLE
PianOli on Google Play Store

### ISSUE THREAD

**Issue by nixxo** [nicolasbrailo/PianOli#35]
Hi,

I found PianOli on Google Play Store here: https://play.google.com/store/apps/details?id=com.nicobrailo.pianoliKelsey and it costs 80€ (70£)

@nicolasbrailo  I don't know if it's you or is someone ripping off your work and selling it. I'm just reporting it.

**Comment by nicolasbrailo** [comment]
LOL. That's hilarious, they didn't even take the effort of changing the name. Thanks for reporting, @nixxo.

I don't know if there is much to be done, honestly. It doesn't technically go against the license in the repo (though I guess they don't disclose the origin of the project, which may be considered a breach of license?) and I don't think that we can report a G app developer for being a bit of an asshole (can we?)

I would love to know if they had any sales, though. If they did, I would publish it for 75€ and donate the income to a project that deserves it more :)

**Comment by nixxo** [comment]
I just found it by accident because I didn't have f-droid on my second phone and tried to search PianOli on the Play Store and found it.

**Comment by nicolasbrailo** [comment]
Thanks for bringing it to my attention. It's a bit sad, but I don't know if there is anything that can be done.

**Comment by nicolasbrailo** [comment]
Besides the subscription fee, I didn't want to publish to G-apps because that's extra work; not only in keeping it up to date, but also in handling user feedback and bug reports, something I don't have the bandwidth to do. In retrospect, I guess it was a mistake to not reserve at least the package name :)

**Comment by pserwylo** [comment]
@nicolasbrailo - The package name used by this person is `com.nicobrailo.pianoliKelsey` so at least they haven't prevented this from being put on Google Play.

If you like (absolutely no obligation, please don't feel like I'm trying to pressure one way or the other), I'd be happy to put the F-Droid build up on Google Play and maintain it. The only catch is that it will be shown as an app by the developer "Peter Serwylo", which is very unfair given you built this great app. Here is a screenshot of how [Lexica looks on Google Play](https://play.google.com/store/apps/details?id=com.serwylo.lexica) (note the "More by Peter Serwylo" which is not ideal for free software apps with multiple contributors and maintainers):

![image](https://user-images.githubusercontent.com/248565/151155402-3a46d0c1-f0da-4588-a86f-ef6175fc7d8a.png)

Some notes:
* All of my apps are the exact binary built and signed by F-Droid. I have more faith in CiaranG's ability to manage signing keys than myself. It also helps with people in the community (if they are particularly technically minded) to verify that I'm not putting crapware in the play store.
* Although some of my free software apps are for a price (essentially a donation for those who don't use F-Droid), Lexica is for free on the Play Store. [Once an app is marked as free, you are unable to ever change it to paid](https://support.google.com/googleplay/android-developer/answer/6334373?hl=en), so there is no risk that PianOli would ever be turned into a weird cashcow for myself or others.
* Lexica has approx 4000 downloads, and there is only a total of about 50 ratings and 20 reviews. I treat the reviews as I do feedback on GitHub (often linking to github issues or creating github issues based on feedback if it is appropriate). I'd be happy to do the same for PianOli too.
* I prioritise the F-Droid releases, so sometimes Google Play lags behind. When I get a buzz of energy, I go download the latest binary from F-Droid and publish it as a new release on Google Play.

As I said - no obligation - really don't mind either way - but the offer is there if you want.

**Comment by nicolasbrailo** [comment]
@pserwylo your offer is incredibly kind. I think it'd be great if you could host it with your account. I don't mind that you'll be listed as the author. I don't expect to become famous for this app, besides you probably contributed enough code to be considered an author anyway.

Would you be OK publishing this app for free?

For the record: I'm not against monetizing apps, I just believe that the reward would be less than the hassle in my personal situation, and also that whoever chose to charge 80 euros for this app is only trying to scam people :)

**Comment by pserwylo** [comment]
Cool, I'll give it a whirl. I've forgotten that since August 2021, new requirements don't actually allow newly added apps to be uploaded as `.apk` files, nor can you manage your own signing keys directly. Rather, I will actually build from source and upload a `.aab` file from my machine.

The process of them forcing control over signing keys irks me (for software freedom reasons), but it isn't like we're pushing new releases every week, so still more than happy to do so.

I'll push a PR soon bumping the targetSdk (not minSdk) to 30 to satisfy this additional requirement they have too:

https://developer.android.com/google/play/requirements/target-sdk

**Comment by nicolasbrailo** [comment]
Thanks! If that's more worked than you were anticipating and would rather not do it, I understand.

**Comment by pserwylo** [comment]
All good. Next hurdle:

![image](https://user-images.githubusercontent.com/248565/151332744-09a5d09a-9691-4454-b251-c421d35acf5a.png)

So there you go, perhaps someone did try to upload it in the past. Google is famous for their lack of human support, so I'll also append a .gplay or something to the `applicationId` in `build.gradle` and see how that goes. Weird, because https://play.google.com/store/apps/details?id=com.nicobrailo.pianoli doesn't work for me. Perhaps someone started the process of uploading it but stopped miway. Either way, easier to just tweak the appId. In fact, I think I prefer this approach, because I'm not able to use the F-Droid signed version so it is kind of nice to show that it is technically a slightly different package.

**Comment by pserwylo** [comment]
Off we go.

![image](https://user-images.githubusercontent.com/248565/151336024-8b34cc8c-65f0-4d8a-afbe-71f11dacff76.png)

The first release can take a few days to get off the ground (subsequent updates are typically within a few hours).

I'll post back here when it is live.

**Comment by nicolasbrailo** [comment]
Thank you so much!

**Comment by pserwylo** [comment]
And we are live!

If you have a Google account and Google Play on your phone, please do download and rate 5 stars. A small number of downloads, ratings, and reviews should be enough to surpass the weird $150 version in search results in short time.

https://play.google.com/store/apps/details?id=com.nicobrailo.pianoli.gplay

I'll do my best to keep this in sync with F-Droid versions, but please don't ever feel bad about pinging me here and asking if I can update it if I forget.

**Comment by nicolasbrailo** [comment]
Just rated it myself, which feels a bit like the meme of Obama giving himself a medal :)

Thanks a lot @pserwylo!

**Comment by nixxo** [comment]
Done as well. And also gave a negative review to the scam App.

**Comment by pserwylo** [comment]
Quick update - thanks to all here who participated! Now have 6 downloads, 5 x 5 star ratings, and 3 x positive reviews. When we first went live, a search for "PianOli" on Google Play would show us about three pages down in the results for some strange reason. Now we have already almost surpassed the scam app - although it is clear from this search result which I would install if I came across this search page :)

![image](https://user-images.githubusercontent.com/248565/152137525-8534d680-b172-4129-a5dd-c9d0e0aff1da.png)

For those unaware - Google updates stats in batches every few days, hence the lack of any star ratings on that search page. It will come with time.

**Comment by pserwylo** [comment]
If anyone is curious, we are close to 1000 downloads on the Play Store. Should happen in less than a month. I am excited for this, because it then shows the app in search results as "1k+ downloads" instead of "500+ downloads" which makes it sound super popular ;)

<kbd>![image](https://github.com/nicolasbrailo/PianOli/assets/248565/84c7e492-d9ca-413b-8dab-eca5bc9d512f)</kbd>

For those who want to see behind the curtain and see what I see when I log into the "Google Play Console", here is a couple of screenshots of the stats:

## In total

955 total downloads.

<kbd>![image](https://github.com/nicolasbrailo/PianOli/assets/248565/555b34e7-7749-496a-be4c-98f4509276ef)</kbd>

Ignore the high number of crashes, these are just when people quit the app, so nobody will ever actually see the crash!

## Each month

Average approx 80 downloads:

<kbd>![image](https://github.com/nicolasbrailo/PianOli/assets/248565/8e8b5622-28f0-4fe4-b995-6e98bcadbd62)</kbd>

**Comment by nicolasbrailo** [comment]
Amazing, thanks @pserwylo !
Do you get a stacktrace with the ANRs? If you do, maybe we should at least track that in a task here? Even if no one will ever see it, we'll know our software is a small tiny little bit better.

**Comment by pserwylo** [comment]
So, funny story. We finally inched over 1k downloads at the rate of one or two per day:

![Screenshot_20231012_091514_org mozilla fennec_fdroid](https://github.com/nicolasbrailo/PianOli/assets/248565/78c950b5-070d-44e2-a3cc-41a742a7c7ca)

Then literally a few days later, there was about 600 downloads in 2 days 🤪. Not sure why. The only other time this happened to an app I published, it was because some youtuber I've never heard of, but who was evidently popular, mentioned it. But I cant see anything on Google for the last week that hints at this sudden spike. 🤷

![Screenshot_20231012_091550_org mozilla fennec_fdroid](https://github.com/nicolasbrailo/PianOli/assets/248565/e30e3c11-d285-4d82-9cb2-b77586ad64af)

Oh well, all just in the name of a bit of fun.

**Comment by pserwylo** [comment]
Weird. It has still kept going. We are now over 5k downloads! Almost all of them this month.

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/4cf8b14c-8076-4a6c-8a9d-1c33058e4eb7)

**Comment by nicolasbrailo** [comment]
Nice! I can't find any relevant links when looking for associated terms, other than this github repo, so it's quite a mystery where the traffic comes from.

**Comment by pserwylo** [comment]
Not slowing down. Over 50k now and still going strong. For those curious, it was particularly popular on Christmas day. I like to think that this is because people got new phones and wanted to experiment with installing cool fun apps. However the cynic in me thinks that it is a way to keep children occupied while adults gather...

Here is the last 3 months as of 2024-01-16:

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/fade64a0-06e6-4c07-a68d-bc26cd70f9c7)

**Comment by juleskers** [comment]
50K+ awesome!

> I like to think that this is because people got new phones and wanted to experiment with installing cool fun apps. However the cynic in me thinks that it is a way to keep children occupied while adults gather...

Perhaps your inner cynic can rest happy that we've given some poor over-stressed parents a brief respite to recharge and heal in a bath of warm family-time :angel: 
(And introduced some kids to interactively making music, which is also educational! And far preferable to *passively* watching cartoons.)

**Comment by pserwylo** [comment]
100k now (the next threshold at which Google Play increments the number of downloads to the end user). Here are stats for the last 3 months as of this comment:

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/cb416963-8304-4567-8057-e395bb54aff0)
