### ISSUE TITLE
Notes are a minor third off

### ISSUE THREAD

**Issue by rharkes** [nicolasbrailo/PianOli#38]
When I play a F on the keyboard I hear a D. Is this intentional?

**Comment by nicolasbrailo** [comment]
Thanks for reporting @rharkes. Certainly not intentional. Would you mind checking here if the notes sound fine? https://github.com/nicolasbrailo/PianOli/tree/master/app/src/main/assets/sounds

It's entirely possible we either have an off by one error, or that I just made a mistake when creating the soundset. Is the problem present for all instruments?

Thanks!

**Comment by rharkes** [comment]
No, all of them give a 220Hz pitch when playing the lowest note it seems. That's one octave below 440Hz, so an A. But the lowest note is a C on the keyboard.

**Comment by rharkes** [comment]
The easiest fix might be to start with an A instead of a C, by changing where you put the black key's in the octave.
https://github.com/nicolasbrailo/PianOli/blob/master/app/src/main/java/com/nicobrailo/pianoli/Piano.java#L113
`if (octave_idx == 1 || octave_idx == 5) {`
But I haven't tested this at all.
