### ISSUE TITLE
Someone stole the code and resells it for a totally honest $94.99

### ISSUE THREAD

**Issue by Magneticdud** [nicolasbrailo/PianOli#41]
... i am really speechless how much selfish and ***hole some people could be

they did not even bother to change the app name... just compile=>publish

https://play.google.com/store/apps/details?id=com.nicobrailo.pianoliKelsey

no attribution at all

Flagged to google play, but we all know google has like 2 human employees behind the play store... maybe someone else know how to report this to some human google employee...

**Comment by Magneticdud** [comment]
Ooops sorry, i watched if it was mentioned and i didn't see it at first glance

Well, the silver lining it's that between all the FOSS apps in the world she could steal, she chose just yours and the other one, so it's a testament that you did a good job :D

**Comment by nicolasbrailo** [comment]
Thanks Jules, I really appreciate all the support in this thread. There is, unfortunately, nothing that can be done about it. The author of the commercial app did build it, from sources built by someone else, and while morally quite reprehensible, there is nothing in the licensing terms of this app or Google's app store that's against it. The only thing we can hope is that the people who paid 100$ for an open source app actually requested a refund.

**Comment by pserwylo** [comment]
...and for those interested, the real version (linked to from the readme of this repo) is doing quite nicely if I do say so:

<kbd>![Screenshot_20220916_211521](https://user-images.githubusercontent.com/248565/190627221-112515af-d5b0-47ae-a96b-5fa63b5d8690.jpg)</kbd>

Due to this support and continued downloads from those interested, a search will almost always show the official version over this weird dodgey one. 

Also for those interested, the fact it has "installs" doesn't *neccesarily* mean people were duped into paying (though I really just don't know). The reason I say this is I have a few free software apps on F-Droid that I put on Google Play for a price of $1 as a form of donation. Each month the Play Store lets you put apps on sale for free for up to one week. I do this to selfishly bump the downloads and make them look more popular by letting anyone download for free. After the sale is over, it kind of looks like they all just paid full price.
