### ISSUE TITLE
Look for new soundpacks

### ISSUE THREAD

**Issue by nicolasbrailo** [nicolasbrailo/PianOli#5]
Freesound seems to be OK. Try to find new sounds @ https://freesound.org/help/faq/#licenses

**Comment by nicolasbrailo** [comment]
Latest release adds a new soundpack. I recorded that one myself, so the quality is pretty horrible.

**Comment by TjlHope** [comment]
Have you considered using a midi driver instead? Then rather than playing individual files, you can instruct it to synth the notes as required, and there's a fairly extensive default set of instruments.
Billthefarmer has done some excelent work packaging a fully featured midi driver, and a few projects you could possibly use as inspiration, e.g: https://github.com/billthefarmer/accordion

**Comment by TjlHope** [comment]
Or I found http://theremin.music.uiowa.edu/MIS.html which seem to be freely usable.
(Found as it's used by another project with a piano built in: https://github.com/tckmn/semitone/blob/master/src/main/assets/about.html)
(PS it's a pain to navigate on a touchscreen as the menus use hover)

**Comment by nicolasbrailo** [comment]
Thanks for the links @TjlHope, they are very useful.
A synth like library was an idea at some point, but it was faster for me to use sound samples. Maybe an idea for a future rewrite. (Also more than happy to accept pull requests in that direction!)

**Comment by TjlHope** [comment]
Yeh sorry, if I manage to find time I'll definitely have a play using synth, but our first is only 2 weeks old. Sleep, let alone time to code, seems to be a thing of the past ATM!

**Comment by nicolasbrailo** [comment]
@TjlHope it gets better :)

**Comment by nicolasbrailo** [comment]
Added new sounds last release
