### ISSUE TITLE
Pinning Bugs & Maybe a different child lock?

### ISSUE THREAD

**Issue by a-raccoon** [nicolasbrailo/PianOli#7]
There seems to be a bug in the way PianOli tries to pin the app and childproof itself.  And I thought I might propose a different unlocking mechanism since this one seems a bit squirrelly and may not necessary stop babies.
```
Screen is pinned
This keeps it in view until you unpin.
Touch & hold Back to unpin.
            NO THANKS    GOT IT
```
The first thing I notice is that this design is a bit confusing.  It makes a matter-of-fact statement and then asks the user to decide if these facts are agreeable to them.  Then I notice that IT sometimes gets confused and behaves differently for either button I push, seemingly randomly pinning or not (between sessions or app kills?).

Then there's a multi-push `EXIT` box that begs to be tapped by small children and adults alike, whether or not the app gets pinned.  I'm not sure if pinning and exit buttons are supposed to go together or be two mutually exclusive features.

I would suggest getting rid of the no-thanks/got-it and display this prompt instead, just below the black keys:
```
Childproof
Touch & hold any 3 black keys for 3 seconds to exit.
Try it now to make sure you've got it . . .
```
This should also play a unique melody so that adults in earshot can tell if the child happens to exit the app.

Sorry for mish-mashing bug reports with feature suggestions.

**Comment by nicolasbrailo** [comment]
Hi @a-raccoon! Thanks for the feedback. Keep it coming! Since I don't publish this app in Google's playstore, bug reports are a nice way to know people keep using this app.

Unfortunately, the app-pinning dialog can't be changed. This is an Android-feature, not an app-feature: https://support.google.com/android/answer/6118421 - PianOli simple "tells" Android "hey, please pin me". The actual message displayed to the user and the behavior of each button is Android-specific (I have a slightly different text in my devices!)

> I would suggest getting rid of the no-thanks/got-it and display this prompt instead, just below the black keys:

There's no way to get rid of the dialog (that's a security feature from Android!) but I like the idea of pressing 3-black keys as a sort of config button. I'll check how feasible that is.

> This should also play a unique melody so that adults in earshot can tell if the child happens to exit the app.

That's clever. Love this one!

**Comment by a-raccoon** [comment]
I have to ask then if app pinning is really necessary.  While prodding at this, I notice it causes some ill effects with my phone, on Android 8.1.0 (LOS 15.1).

The screen flickers when it does pinning, making the app look like it's reloading.
If I hit back during this process, I end up on my home screen -- pinned -- can't do anything until I hold back for several seconds.
In about a 1 dozen app launches and exits,, I crashed and auto-rebooted the phone 3 times.

I don't know of any other apps that use pinning.

**Comment by a-raccoon** [comment]
I guess in older versions of Android, it was fairly easy to rewrite or @override the back/home/recent keys, and notify/status gestures.  It seems that MX Player is renowned for writing their own child lock, variously UI drawing, without pinning.

**Comment by Biont** [comment]
Thank you very much for making this app.

I would like to add that the multi-button-unlock is too easy to keep babies from unlocking very long. Closing the app soon becomes the preferred way of interacting with it (let's say around the 15 month mark) because it's just so tempting to follow that button around.

I am not sure if this feature is really needed since you can always unlock via the stock method (which is far too easy to figure out as well actually).

If the feature is to stay, then I'd propose to make it more difficult. Maybe something like this:

* first press adds 2 new buttons randomly
* second press adds 3 buttons randomy
* third press adds 4 buttons randomly in all corners
* only one of the buttons actually proceeds for each iteration, the others reset the lock

This way you need to be able to read numbers and count. So it should work a bit longer

**Comment by nicolasbrailo** [comment]
Commit 12a4d98 implements new childlock
