### ISSUE TITLE
Cannot read tooltip about how to get to settings after tapping cog once

### ISSUE THREAD

**Issue by pserwylo** [nicolasbrailo/PianOli#77]
By design, the tooltip explaining how to visit settings is only shown the first time somebody taps the cog icon:

https://github.com/nicolasbrailo/PianOli/blob/4f7a6a80038d716ecfc59e09654804755b36bd23/app/src/main/java/com/nicobrailo/pianoli/AppConfigTrigger.java#L79-L82

However, two anecdotes make me think perhaps we should *always* show the tooltip when the icon is pressed.

Firstly - there are a few reviews on Google Play saying the app is hard to unlock. Originally, I had a little chuckle and thought to myself "good! the app is working as intended!". However, my second observation came a couple of days ago when I demoed the app to a fellow computer science nerd dad. He tapped the cog, saw the message but didn't read it. Then tried to tap it again but nothing happened. Then he spent about a minute stuffing about trying to figure out what to do next.

Given that it doesn't really stop the app from working as a piano, can we show the toast every time someone taps the cog?

Two extra improvements may make this more palatable:
 * Instead of tapping **the black key with the cog on it**, tap **the actual cog**. That way, it will be less likely that kids will bring up the toast message when mashing keys (though of course it will still happen).
 * Change the length of the toast from `LENGTH_LONG` to `LENGTH_SHORT`. If it is easy for the message to be shown again, then there is no need for it to hang around for a long time taking up space over our precious keys.

Thoughts?

**Comment by juleskers** [comment]
Oh! I like both of your suggestions!  
- Tap the actual cog: I don't think I've *ever* tapped the keys-but-not-the-cog when I wanted to go into settings..
- Length_short: sounds good!
  - especially when combined with the cog-itself tap, it should massively reduce the spam-count. 

Still, I am a bit worried that the toast takes up some *prime* real-estate in the dead center of the keys, exactly where the normal focus of a user is ( That's their designed goal, after all. ) 

It worries me because I already find myself wanting to tap toasts in general (to make it go away), but since it doesn't interact, that feels micro-frustrating. That's not a feeling I want a child to get when interacting with devices in general, and PianOli specifically. 

My worry is, that if the toast can re-appear, key mashing could spam it so often that it becomes distracting, and the interaction mode switches from "ooh, keys make pretty sounds" to "make the grey blob appear and try to make it do something". 

I'm not sure how valid that concern is. Am I being to prescriptive in how the app "should" be used? 


Perhaps a rate-limit is in order? Only every N milliseconds? Or every M cog-taps? 

On second thought, I think we can follow "user frustration" with a fairly simple rule: only repeat the toast after N (3? 5?) taps of the cog-key (entire key? Cog only?), and reset the counter on any other keys. 
This should prevent most recurrence for normal mashing, but help a targeted-hitting adult who is struggling.

**Comment by nicolasbrailo** [comment]
> only repeat the toast after at least N (3? 5?) taps of the cog-key (entire key? Cog only?), and reset the counter on any other keys.

That sounds like a brilliant suggestion by @juleskers !

**Comment by juleskers** [comment]
I've taken a stab at this in my "holiday hacking" time.
MR #84 reshows the toast if 
- *only* cog keys are hit
- at least 5
- within a 5 second window.

Any non-cog-key will reset the counter, as well as actually showing the toast. (fun anecdote: before the reset-on-show, I managed to hit so many config keys, that the toast-backlog kept spamming a full minute after I stopped touching the screen 😅) 

I haven't taken a stab at making the cog a separate touch-area, distinct from the rest-of-the-key.
I think that's still a good idea, but it's an even larger refactoring, since the gears would need to gain their own touch-event handling.
That feels like a fairly "expensive" change. Before going down that path, I wanted to see how well this works, first.
