### ISSUE TITLE
ability to unpin app more easily in settings

### ISSUE THREAD

**Issue by RustoMCSpit** [nicolasbrailo/PianOli#92]

**Comment by RustoMCSpit** [comment]
i hate the pinning feature, it for some reason causes my device to end up in the lock screen too?

**Comment by pserwylo** [comment]
Thanks for the report @RustoMCSpit. Sending you back to the lock screen is a feature of the Android OS used by your phone. I assume it is so that if a kid is playing in the back seat while you are driving, and then they accidentally (or intentionally 🤪) unpin the app, then they can't start ordering Uber Eats without you first unlocking for them.

For now, I will close this and fefer to #12 which (despite its name) is a discussion place for all things unpin/unlock related.

**Comment by RustoMCSpit** [comment]
@pserwylo okay added to that
